# Generated by Django 6.0 on 2026-01-03 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(help_text='Write your post in Markdown format')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('is_about_page', models.BooleanField(default=False, help_text='Check this to make this post the About Me page (only one should be checked)')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
