# Generated by Django 6.0 on 2026-01-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail for blog list', null=True, upload_to='thumbnails/%Y/%m/'),
        ),
    ]
